#!/bin/bash

mypath=${0%/*}
pushd $mypath
module=${1}
srcpth=${module//.//}
srcdir=../${srcpth%/*}
testnm=${srcpth##*/}_test
rm -f ${testnm}{,.d,.o}
echo "module ${testnm};"      > ${testnm}.d
echo "import std.typetuple;" >> ${testnm}.d
inputs=""
let status=0
for i in $(ls ${srcdir}/*.d) ; do
    obj=${i/.d/.o}
    obj=${obj##*/}
    if [ ${i} != ../${srcpth}.d ]; then
        dmd -w -I.. -I~/.dub/packages/{derelict-util-1.9.1/source,derelict-cl-1.2.2/source,pegged-0.2.1}                                   -c ${i}
        let excode=$?
        let status=$((status||excode))
    else
        dmd -w -I.. -I~/.dub/packages/{derelict-util-1.9.1/source,derelict-cl-1.2.2/source,pegged-0.2.1} -unittest -version=UNITTEST_DEBUG -c ${i}
        let excode=$?
        let status=$((status||excode))
    fi
    inputs="${inputs} ${obj}"
    import=${i#*/}
    import=${import%.d}
    import=${import//\//.}
    echo "static import ${import};" >> ${testnm}.d
done
echo "alias allModules = TypeTuple!(${module});" >> ${testnm}.d
cat >> ${testnm}.d <<EOF
void main()
{
  import std.stdio;
  writeln("All unit tests have been run successfully.");
}
EOF
if [ ! -f ../lib/libclop_runtime.a ] ; then
    pushd ..
    dub build --build=debug :runtime
    popd
fi

if [ $((status)) = 0 ]; then
    dmd -w -I.. -I~/.dub/packages/{derelict-util-1.9.1/source,derelict-cl-1.2.2/source,pegged-0.2.1} \
        -unittest -version=UNITTEST_DEBUG -of${testnm} ${testnm}.d ${inputs} \
        ~/.dub/packages/{pegged-0.2.1/libpegged.a,derelict-cl-1.2.2/lib/libDerelictCL.a,derelict-util-1.9.1/lib/libDerelictUtil.a} \
        ../lib/libclop_runtime.a -L-ldl
    let excode=$?
    let status=$((status||excode))
fi
# finally run the unit tests, if everything compiled without errors.
if [ $((status)) = 0 ]; then
    ./${testnm}
    let status=$?
fi
popd
exit ${status}

# Local Variables:
# mode: bash
# End:
